// Generated by tools/build.js from site.config.json.
// Runs on Cloudflare Pages in front of every request:
//  - http:// -> https:// (301), in case "Always Use HTTPS" is ever switched off
//  - www. and *.pages.dev production traffic -> the canonical domain (301)
//  - preview deployments (branch.*.pages.dev) stay reachable but are hidden from search engines
const CANONICAL = "senayamyers27-art.github.io";
const REDIRECT_WWW = true;

export async function onRequest({ request, next }) {
  const url = new URL(request.url);
  const host = url.hostname;
  const isPreview = /^[^.]+\.[^.]+\.pages\.dev$/.test(host);
  let target = null;
  if (url.protocol === "http:" && host !== "localhost" && host !== "127.0.0.1") target = new URL(url);
  if (CANONICAL && !isPreview && host !== CANONICAL && (host.endsWith(".pages.dev") || (REDIRECT_WWW && host === "www." + CANONICAL))) {
    target = new URL(url); target.hostname = CANONICAL;
  }
  if (target) { target.protocol = "https:"; target.port = ""; return Response.redirect(target.toString(), 301); }
  const res = await next();
  if (isPreview) { const r = new Response(res.body, res); r.headers.set("X-Robots-Tag", "noindex, nofollow"); return r; }
  return res;
}
