#!/usr/bin/env node
/* Writes api/wrangler.deploy.toml for the accounts API from site.config.json and environment
   variables, so no account-specific ids live in the repository.
   Needs: STUDY_API_D1_ID. Optional: STUDY_API_R2_BUCKET, STUDY_API_EMAIL_FROM,
   STRIPE_PRICE_PRO_MONTHLY, STRIPE_PRICE_PRO_YEARLY, STRIPE_PRICE_PREMIUM_MONTHLY, STRIPE_PRICE_PREMIUM_YEARLY,
   STRIPE_PRICE_ORG_SEAT, STRIPE_TAX, STRIPE_PORTAL_CONFIG. */
const fs = require("fs"), path = require("path");
const ROOT = path.join(__dirname, "..");
const cfg = JSON.parse(fs.readFileSync(path.join(ROOT, "site.config.json"), "utf8"));
const die = m => { console.error(m); process.exit(1); };

const domain = String(cfg.domain || "").trim().toLowerCase().replace(/^https?:\/\//, "").replace(/\/.*$/, "");
const api = String(cfg.apiOrigin || "").trim().replace(/\/+$/, "").toLowerCase();
if (!domain) die("Set \"domain\" in site.config.json first: accounts need the site on its own domain.");
if (!/^https:\/\/[a-z0-9.-]+$/.test(api)) die("Set \"apiOrigin\" in site.config.json to https://api.<your domain>.");
const apiHost = api.slice(8), base = domain.replace(/^www\./, "");
// The session cookie only works when the API is on the same site as the pages.
if (apiHost !== base && !apiHost.endsWith("." + base)) die(`apiOrigin ${api} must be a subdomain of ${base} (for example https://api.${base}).`);
// Pasted values often carry spaces, quotes, a line break or capitals; take the UUID out of whatever was pasted.
// STUDY_API_D1_ID_FOUND: the id the deploy workflow looked up by name when STUDY_API_D1_ID didn't hold one.
const d1 = ((process.env.STUDY_API_D1_ID_FOUND || process.env.STUDY_API_D1_ID || "").match(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i) || [""])[0].toLowerCase();
if (!d1) die("STUDY_API_D1_ID must be the D1 database id: a UUID like 8837b692-ac42-41e5-a1f3-22f7e405f1bb (Cloudflare → D1 → your database).");

const q = s => JSON.stringify(String(s));
const vars = {
  APP_ENV: "production",
  SITE_ORIGIN: `https://${domain}`,
  // "Name<address>" and stray spaces are tidied into "Name <address>".
  EMAIL_FROM: (process.env.STUDY_API_EMAIL_FROM || "").trim().replace(/\s*<\s*/, " <").replace(/\s*>\s*$/, ">") || `${cfg.siteName} <signin@${base}>`,
  STRIPE_TAX: process.env.STRIPE_TAX === "on" ? "on" : "off"
};
for (const k of ["STRIPE_PRICE_PRO_MONTHLY", "STRIPE_PRICE_PRO_YEARLY", "STRIPE_PRICE_PREMIUM_MONTHLY", "STRIPE_PRICE_PREMIUM_YEARLY", "STRIPE_PRICE_ORG_SEAT"])
  if (/^price_[A-Za-z0-9]+$/.test(process.env[k] || "")) vars[k] = process.env[k];
if (/^bpc_[A-Za-z0-9]+$/.test(process.env.STRIPE_PORTAL_CONFIG || "")) vars.STRIPE_PORTAL_CONFIG = process.env.STRIPE_PORTAL_CONFIG;
// The site owner's dashboard (#admin): comma-separated email addresses from the STUDY_API_ADMIN_EMAILS variable.
const admins = (process.env.STUDY_API_ADMIN_EMAILS || "").split(",").map(s => s.trim().toLowerCase()).filter(s => /^[^\s@]+@[^\s@]+\.[a-z]{2,}$/.test(s));
if (admins.length) vars.ADMIN_EMAILS = admins.join(",");

// One compatibility date for local and deployed Workers: the one in api/wrangler.toml.
const compat = (fs.readFileSync(path.join(ROOT, "api/wrangler.toml"), "utf8").match(/^compatibility_date\s*=\s*"(\d{4}-\d{2}-\d{2})"/m) || [])[1];
if (!compat) die("api/wrangler.toml needs a compatibility_date.");

let toml = `# Generated by tools/api-config.js. Not committed.
name = "cyber-cert-study-api"
main = "src/index.js"
compatibility_date = "${compat}"
workers_dev = false
routes = [{ pattern = ${q(apiHost)}, custom_domain = true }]

[vars]
${Object.entries(vars).map(([k, v]) => `${k} = ${q(v)}`).join("\n")}

# Per-address request limit at the edge (API_LIMIT in src/index.js).
[[ratelimits]]
name = "API_LIMIT"
namespace_id = "1001"
simple = { limit = 120, period = 60 }

# Daily clean-up of expired sign-in links, sessions and old logs.
[triggers]
crons = ["23 4 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "cyber-cert-study"
database_id = ${q(d1)}
migrations_dir = "migrations"
`;
const r2 = (process.env.STUDY_API_R2_BUCKET || "").trim().replace(/^["']|["']$/g, "");
if (r2) {
  if (!/^[a-z0-9-]{3,63}$/.test(r2)) die("STUDY_API_R2_BUCKET is not a valid bucket name.");
  toml += `\n[[r2_buckets]]\nbinding = "CONTENT"\nbucket_name = ${q(r2)}\n`;
}
fs.writeFileSync(path.join(ROOT, "api/wrangler.deploy.toml"), toml);
console.log(`Wrote api/wrangler.deploy.toml for ${api} (site https://${domain}).`);
