#!/usr/bin/env node
/* Writes api/wrangler.deploy.toml for the accounts API from site.config.json and environment
   variables, so no account-specific ids live in the repository.
   Needs: STUDY_API_D1_ID. Optional: STUDY_API_R2_BUCKET, STUDY_API_EMAIL_FROM,
   STRIPE_PRICE_PRO_MONTHLY, STRIPE_PRICE_PRO_YEARLY, STRIPE_PRICE_ORG_SEAT, STRIPE_TAX. */
const fs = require("fs"), path = require("path");
const ROOT = path.join(__dirname, "..");
const cfg = JSON.parse(fs.readFileSync(path.join(ROOT, "site.config.json"), "utf8"));
const die = m => { console.error(m); process.exit(1); };

const domain = String(cfg.domain || "").trim().toLowerCase().replace(/^https?:\/\//, "").replace(/\/.*$/, "");
const api = String(cfg.apiOrigin || "").trim().replace(/\/+$/, "").toLowerCase();
if (!domain) die("Set \"domain\" in site.config.json first: accounts need the site on its own domain.");
if (!/^https:\/\/[a-z0-9.-]+$/.test(api)) die("Set \"apiOrigin\" in site.config.json to https://api.<your domain>.");
const apiHost = api.slice(8), base = domain.replace(/^www\./, "");
// The session cookie only works when the API is on the same site as the pages.
if (apiHost !== base && !apiHost.endsWith("." + base)) die(`apiOrigin ${api} must be a subdomain of ${base} (for example https://api.${base}).`);
const d1 = process.env.STUDY_API_D1_ID || "";
if (!/^[0-9a-f-]{36}$/.test(d1)) die("STUDY_API_D1_ID must be the D1 database id (a UUID).");

const q = s => JSON.stringify(String(s));
const vars = {
  APP_ENV: "production",
  SITE_ORIGIN: `https://${domain}`,
  EMAIL_FROM: process.env.STUDY_API_EMAIL_FROM || `${cfg.siteName} <signin@${base}>`,
  STRIPE_TAX: process.env.STRIPE_TAX === "on" ? "on" : "off"
};
for (const k of ["STRIPE_PRICE_PRO_MONTHLY", "STRIPE_PRICE_PRO_YEARLY", "STRIPE_PRICE_ORG_SEAT"])
  if (/^price_[A-Za-z0-9]+$/.test(process.env[k] || "")) vars[k] = process.env[k];

let toml = `# Generated by tools/api-config.js. Not committed.
name = "cyber-cert-study-api"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = false
routes = [{ pattern = ${q(apiHost)}, custom_domain = true }]

[vars]
${Object.entries(vars).map(([k, v]) => `${k} = ${q(v)}`).join("\n")}

[[d1_databases]]
binding = "DB"
database_name = "cyber-cert-study"
database_id = ${q(d1)}
migrations_dir = "migrations"
`;
const r2 = process.env.STUDY_API_R2_BUCKET || "";
if (r2) {
  if (!/^[a-z0-9-]{3,63}$/.test(r2)) die("STUDY_API_R2_BUCKET is not a valid bucket name.");
  toml += `\n[[r2_buckets]]\nbinding = "CONTENT"\nbucket_name = ${q(r2)}\n`;
}
fs.writeFileSync(path.join(ROOT, "api/wrangler.deploy.toml"), toml);
console.log(`Wrote api/wrangler.deploy.toml for ${api} (site https://${domain}).`);
