#!/usr/bin/env node
/* Splits the lessons in content/lessons(-es)/<id>.js into what the public site serves and what only
   signed-in members get.

   With accounts on (site.config.json "apiOrigin"), public/data/lessons(-es)/<id>.js keeps the first
   FREE lessons of each certification whole (the signed-out sample, the same ones the static lesson pages
   show in full) and only the title and opening paragraph of the rest, marked `locked`. The full text of
   the locked lessons goes to member/lessons(-es)/<id>.json, which the API deploy uploads to the private
   R2 bucket and the API hands only to signed-in accounts (GET /v1/content/lessons/<id>). Without
   accounts, the public files carry every lesson in full.

     node tools/lesson-split.js --member   write member/ only (the API deploy uses this)

   tools/build.js calls split() to write the public files. */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "content");
const MEMBER = path.join(ROOT, "member");
const FREE = 2;
const DIRS = ["lessons", "lessons-es"];

function apiOriginOf() {
  const cfg = JSON.parse(fs.readFileSync(path.join(ROOT, "site.config.json"), "utf8"));
  return String(cfg.apiOrigin || "").trim();
}

// Reads one source file; returns { id, list, meta } or null.
function read(dir, id) {
  const f = path.join(SRC, dir, id + ".js");
  if (!fs.existsSync(f)) return null;
  let got = null;
  const prev = global.CertHub;
  global.CertHub = { addLessons: (i, list, meta) => { got = { id: i, list, meta: meta || {} }; } };
  try { new Function(fs.readFileSync(f, "utf8"))(); } finally { global.CertHub = prev; }
  if (!got || got.id !== id || !Array.isArray(got.list)) throw new Error(`${path.relative(ROOT, f)} must call CertHub.addLessons("${id}", [...])`);
  return got;
}

const ids = dir => fs.existsSync(path.join(SRC, dir)) ? fs.readdirSync(path.join(SRC, dir)).filter(f => /^[a-z0-9-]+\.js$/.test(f)).map(f => f.slice(0, -3)).sort() : [];

// The English file decides which lessons are free (by topic text), so a translation locks the same ones.
function freeTopics(id) {
  const en = read("lessons", id);
  return new Set((en ? en.list : []).slice(0, FREE).map(l => l.t));
}

const stub = l => {
  const s = { t: l.t };
  if (l.tt) s.tt = l.tt;
  if (l.hook) s.hook = l.hook; // the story opener stays as a teaser
  const first = Array.isArray(l.body) ? l.body.find(p => typeof p === "string" && !/^```/.test(p)) : "";
  s.body = first ? [first] : [];
  s.locked = true;
  return s;
};

// Returns { public: { "public/data/lessons/<id>.js": text }, member: { "member/lessons/<id>.json": text } }.
function split(apiOrigin = apiOriginOf()) {
  const res = { public: {}, member: {} };
  for (const dir of DIRS) for (const id of ids(dir)) {
    const src = read(dir, id);
    const free = freeTopics(id);
    const locked = apiOrigin ? src.list.filter(l => !free.has(l.t)) : [];
    const list = apiOrigin ? src.list.map(l => free.has(l.t) ? l : stub(l)) : src.list;
    res.public[`public/data/${dir}/${id}.js`] = `/* Generated by tools/build.js from content/${dir}/${id}.js. Edit that file, not this one. */\nCertHub.addLessons(${JSON.stringify(id)}, ${JSON.stringify(list)}, ${JSON.stringify(src.meta)});\n`;
    if (locked.length) res.member[`member/${dir}/${id}.json`] = JSON.stringify({ id, lang: dir === "lessons-es" ? "es" : "en", lessons: locked });
  }
  // Teacher editions (content/teacher/<id>.js): never public; the API serves them to teacher accounts.
  for (const id of teacherIds()) res.member[`member/teacher/${id}.json`] = JSON.stringify({ id, plans: readTeacher(id) });
  return res;
}

// content/teacher/<id>.js calls CertHub.addTeacher(id, [{ t, objectives, plan, warmup, activity, discussion, exit, differentiation }]).
const teacherIds = () => ids("teacher");
function readTeacher(id) {
  const f = path.join(SRC, "teacher", id + ".js");
  let got = null;
  const prev = global.CertHub;
  global.CertHub = { addTeacher: (i, list) => { got = { id: i, list }; } };
  try { new Function(fs.readFileSync(f, "utf8"))(); } finally { global.CertHub = prev; }
  if (!got || got.id !== id || !Array.isArray(got.list)) throw new Error(`content/teacher/${id}.js must call CertHub.addTeacher("${id}", [...])`);
  return got.list;
}

function writeMember(res) {
  fs.rmSync(MEMBER, { recursive: true, force: true });
  for (const [rel, text] of Object.entries(res.member)) {
    const f = path.join(ROOT, rel);
    fs.mkdirSync(path.dirname(f), { recursive: true });
    fs.writeFileSync(f, text);
  }
}

module.exports = { split, writeMember, readTeacher, teacherIds, FREE };

if (require.main === module && process.argv.includes("--member")) {
  const res = split();
  writeMember(res);
  console.log(`Wrote ${Object.keys(res.member).length} member lesson bundles to member/.`);
}
